#!/bin/sh

# Check if this is a rack app
if [ -r config.ru ] || [ -d public/ ]; then
  
  # Allow the user to specify a site name, or use the current dir name. Make sure it's lowercase.
  SITE_NAME=$( echo "${1-${PWD##*/}}" | tr -s  '[:upper:]'  '[:lower:]' )
  
  # Symlink current dir if it doesn't already exist
  if [ ! -L ~/.pow/$SITE_NAME ]; then
    ln -s $PWD ~/.pow/$SITE_NAME
  fi
  
  # Open in browser
  open http://$SITE_NAME.dev/
  
else
  
  echo "No config.ru (Rack config file) or public/ dir (static assets) were found"
  
fi